/*
 * @Author: your name
 * @Date: 2021-12-28 09:41:07
 * @LastEditTime: 2021-12-28 09:41:08
 * @LastEditors: Please set LastEditors
 * @Description: 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 * @FilePath: /notion/flexibleMerge.js
 */
// flexible
!function(a,b){function c(){var b=f.getBoundingClientRect().width;b/i>540&&(b=540*i);var c=b/10;f.style.fontSize=c+"px",k.rem=a.rem=c}var d,e=a.document,f=e.documentElement,g=e.querySelector('meta[name="viewport"]'),h=e.querySelector('meta[name="flexible"]'),i=0,j=0,k=b.flexible||(b.flexible={});if(g){console.warn("\u5c06\u6839\u636e\u5df2\u6709\u7684meta\u6807\u7b7e\u6765\u8bbe\u7f6e\u7f29\u653e\u6bd4\u4f8b");var l=g.getAttribute("content").match(/initial\-scale=([\d\.]+)/);l&&(j=parseFloat(l[1]),i=parseInt(1/j))}else if(h){var m=h.getAttribute("content");if(m){var n=m.match(/initial\-dpr=([\d\.]+)/),o=m.match(/maximum\-dpr=([\d\.]+)/);n&&(i=parseFloat(n[1]),j=parseFloat((1/i).toFixed(2))),o&&(i=parseFloat(o[1]),j=parseFloat((1/i).toFixed(2)))}}if(!i&&!j){a.navigator.appVersion.match(/android/gi),a.navigator.appVersion.match(/iphone/gi),a.devicePixelRatio;i=1,j=1/i}if(f.setAttribute("data-dpr",i),!g)if(g=e.createElement("meta"),g.setAttribute("name","viewport"),g.setAttribute("content","initial-scale="+j+", maximum-scale="+j+", minimum-scale="+j+", user-scalable=no"),f.firstElementChild)f.firstElementChild.appendChild(g);else{var r=e.createElement("div");r.appendChild(g),e.write(r.innerHTML)}a.addEventListener("resize",function(){clearTimeout(d),d=setTimeout(c,300)},!1),a.addEventListener("pageshow",function(a){a.persisted&&(clearTimeout(d),d=setTimeout(c,300))},!1),"complete"===e.readyState?e.body.style.fontSize=12*i+"px":e.addEventListener("DOMContentLoaded",function(){e.body.style.fontSize=12*i+"px"},!1),c(),k.dpr=a.dpr=i,k.refreshRem=c,k.rem2px=function(a){var b=parseFloat(a)*this.rem;return"string"==typeof a&&a.match(/rem$/)&&(b+="px"),b},k.px2rem=function(a){var b=parseFloat(a)/this.rem;return"string"==typeof a&&a.match(/px$/)&&(b+="rem"),b}}(window,window.lib||(window.lib={}));

// makegrid
!function(a,b){function c(a){var c=parseFloat(a.designWidth),d=parseFloat(a.designUnit),h=parseFloat(a.columnCount),i=parseFloat(a.columnXUnit),j=parseFloat(a.gutterXUnit),k=parseFloat(a.edgeXUnit),l=a.className||"grid";if(!(a.designWidth&&a.designUnit&&a.columnCount&&a.columnXUnit&&a.gutterXUnit&&a.edgeXUnit))throw new Error("参数错误");b.flexible.gridParams=a;for(var m=d/c*10,n=i*m,o=j*m,p=k*m,q=["."+l+" {","box-sizing:content-box;","padding-left: "+p+"rem;","padding-right: "+p+"rem;","margin-left: -"+o+"rem;","}","."+l+":before,","."+l+":after{",'content: " ";',"display: table;","}","."+l+":after {","clear: both;","}","."+l+' [class^="col-"] {',"margin-left: "+o+"rem;","float: left;","}"],r=1;h>=r;r++){var s=n*r+o*(r-1);q.push("."+l+" .col-"+r+" {width: "+s+"rem;}")}e&&e.parentNode&&e.parentNode.removeChild(e),e=f.createElement("style"),e.innerHTML=q.join("");var t=f.querySelector("head")||g.firstElementChild||g;t.appendChild(e)}function d(a){var b=j[a];if(!b)throw new Error("不支持这个预设模式");c(b)}var e,f=a.document,g=f.documentElement,h=f.querySelector('meta[name="grid"]'),i=b.flexible||(b.flexible={}),j={"750-12":{designWidth:750,designUnit:6,columnCount:12,columnXUnit:7,gutterXUnit:3,edgeXUnit:4},"750-6":{designWidth:750,designUnit:6,columnCount:6,columnXUnit:17,gutterXUnit:3,edgeXUnit:4},"640-12":{designWidth:640,designUnit:4,columnCount:12,columnXUnit:11,gutterXUnit:2,edgeXUnit:3},"640-6":{designWidth:640,designUnit:4,columnCount:6,columnXUnit:24,gutterXUnit:2,edgeXUnit:3}};if(h){var k=h.getAttribute("content");if(k){for(var l,m=/([^=]+)=([\d\.\-]+)/g,n={};l=m.exec(k);)n[l[1]]=l[2];n.modeName?d(n.modeName):c(n)}}i.makeGrid=c,i.makeGridMode=d}(window,window.lib||(window.lib={}));